config/routes.rb
App::Application.routes.draw do
  use_doorkeeper

  resources :team_roles

  resources :people

  resources :teams

  resources :organizations

  root :to => "events#index"
  resources :roles

  resources :authorizations

  devise_for :users #, :controllers => {sessions: "MySessionsController"}

  resources :users
  resources :shifts
  resources :events

  namespace :api, defaults: {format: 'json'} do
    resources :events
  end

end

app/controllers/team_roles_controller.rb
class TeamRolesController < ApplicationController
  # GET /team_roles
  # GET /team_roles.json
  def index
    @team_roles = TeamRole.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @team_roles }
    end
  end

  # GET /team_roles/1
  # GET /team_roles/1.json
  def show
    @team_role = TeamRole.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team_role }
    end
  end

  # GET /team_roles/new
  # GET /team_roles/new.json
  def new
    @team_role = TeamRole.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team_role }
    end
  end

  # GET /team_roles/1/edit
  def edit
    @team_role = TeamRole.find(params[:id])
  end

  # POST /team_roles
  # POST /team_roles.json
  def create
    @team_role = TeamRole.new(params[:team_role])

    respond_to do |format|
      if @team_role.save
        format.html { redirect_to @team_role, notice: 'Team role was successfully created.' }
        format.json { render json: @team_role, status: :created, location: @team_role }
      else
        format.html { render action: "new" }
        format.json { render json: @team_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /team_roles/1
  # PUT /team_roles/1.json
  def update
    @team_role = TeamRole.find(params[:id])

    respond_to do |format|
      if @team_role.update_attributes(params[:team_role])
        format.html { redirect_to @team_role, notice: 'Team role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_roles/1
  # DELETE /team_roles/1.json
  def destroy
    @team_role = TeamRole.find(params[:id])
    @team_role.destroy

    respond_to do |format|
      format.html { redirect_to team_roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/team_roles_helper.rb
module TeamRolesHelper
end

app/views/team_roles/_form.html.erb
<%= form_for(@team_role) do |f| %>
  <% if @team_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_role.errors.count, "error") %> prohibited this team_role from being saved:</h2>

      <ul>
      <% @team_role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_roles/edit.html.erb
<h1>Editing team_role</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_role %> |
<%= link_to 'Back', team_roles_path %>

app/views/team_roles/index.html.erb
<h1>Listing team_roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @team_roles.each do |team_role| %>
  <tr>
    <td><%= team_role.name %></td>
    <td><%= link_to 'Show', team_role %></td>
    <td><%= link_to 'Edit', edit_team_role_path(team_role) %></td>
    <td><%= link_to 'Destroy', team_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Team role', new_team_role_path %>

app/views/team_roles/new.html.erb
<h1>New team_role</h1>

<%= render 'form' %>

<%= link_to 'Back', team_roles_path %>

app/views/team_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @team_role.name %>
</p>


<%= link_to 'Edit', edit_team_role_path(@team_role) %> |
<%= link_to 'Back', team_roles_path %>