config/routes.rb
App::Application.routes.draw do
  use_doorkeeper

  resources :team_roles

  resources :people

  resources :teams

  resources :organizations

  root :to => "events#index"
  resources :roles

  resources :authorizations

  devise_for :users #, :controllers => {sessions: "MySessionsController"}

  resources :users
  resources :shifts
  resources :events

  namespace :api, defaults: {format: 'json'} do
    resources :events
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    logger.info "Caught acception in CanCan"
    if request.env.key? "HTTP_REFERER"
      redirect_to :back, :alert => exception.message
    else
      redirect_to root_url, :alert => exception.message
      # render :text => "#{exception.message}"
    end
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navigation.html.erb
<!-- stuff at the left -->
<ul class="nav">

  <li>
    <%= link_to "Orgs", organizations_path %>
  </li>
  <li>
    <%= link_to "Events", events_path %>
  </li>
  <li>
    <%= link_to "Teams", teams_path %>
  </li>
  <li>
    <%= link_to "Users", users_path %>
  </li>
</ul>

<!-- stuff at the right -->

<span style="float:right">
  <ul class="nav">
    <% if user_signed_in? %>
    <li>
      <%= current_user.name %> (<%=link_to 'Logout', destroy_user_session_path, :method=>'delete' %>, 
      <%= link_to 'Edit account', edit_user_registration_path %>)
    </li>
    <% else %>
    <li>
      <%= link_to 'Login', new_user_session_path %>
    </li>
    <li>
      <%= link_to 'Sign up', new_user_registration_path %>
    </li>
    <% end %>
  </ul>
</span>